"""Bundled ISO 639-2 codes and English names; no system iso-codes dependency.

Includes terminology/bibliographic aliases. Three-letter-only codes stay intact.
Source: ISO 639-2 table distributed by Debian iso-codes.
"""

LANGUAGES = (
    ('aa', 'aar', None, 'Afar'),
    ('ab', 'abk', None, 'Abkhazian'),
    (None, 'ace', None, 'Achinese'),
    (None, 'ach', None, 'Acoli'),
    (None, 'ada', None, 'Adangme'),
    (None, 'ady', None, 'Adyghe; Adygei'),
    (None, 'afa', None, 'Afro-Asiatic languages'),
    (None, 'afh', None, 'Afrihili'),
    ('af', 'afr', None, 'Afrikaans'),
    (None, 'ain', None, 'Ainu'),
    ('ak', 'aka', None, 'Akan'),
    (None, 'akk', None, 'Akkadian'),
    (None, 'ale', None, 'Aleut'),
    (None, 'alg', None, 'Algonquian languages'),
    (None, 'alt', None, 'Southern Altai'),
    ('am', 'amh', None, 'Amharic'),
    (None, 'ang', None, 'English, Old (ca. 450-1100)'),
    (None, 'anp', None, 'Angika'),
    (None, 'apa', None, 'Apache languages'),
    ('ar', 'ara', None, 'Arabic'),
    (None, 'arc', None, 'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)'),
    ('an', 'arg', None, 'Aragonese'),
    (None, 'arn', None, 'Mapudungun; Mapuche'),
    (None, 'arp', None, 'Arapaho'),
    (None, 'art', None, 'Artificial languages'),
    (None, 'arw', None, 'Arawak'),
    ('as', 'asm', None, 'Assamese'),
    (None, 'ast', None, 'Asturian; Bable; Leonese; Asturleonese'),
    (None, 'ath', None, 'Athapascan languages'),
    (None, 'aus', None, 'Australian languages'),
    ('av', 'ava', None, 'Avaric'),
    ('ae', 'ave', None, 'Avestan'),
    (None, 'awa', None, 'Awadhi'),
    ('ay', 'aym', None, 'Aymara'),
    ('az', 'aze', None, 'Azerbaijani'),
    (None, 'bad', None, 'Banda languages'),
    (None, 'bai', None, 'Bamileke languages'),
    ('ba', 'bak', None, 'Bashkir'),
    (None, 'bal', None, 'Baluchi'),
    ('bm', 'bam', None, 'Bambara'),
    (None, 'ban', None, 'Balinese'),
    (None, 'bas', None, 'Basa'),
    (None, 'bat', None, 'Baltic languages'),
    (None, 'bej', None, 'Beja; Bedawiyet'),
    ('be', 'bel', None, 'Belarusian'),
    (None, 'bem', None, 'Bemba'),
    ('bn', 'ben', None, 'Bengali'),
    (None, 'ber', None, 'Berber languages'),
    (None, 'bho', None, 'Bhojpuri'),
    ('bh', 'bih', None, 'Bihari languages'),
    (None, 'bik', None, 'Bikol'),
    (None, 'bin', None, 'Bini; Edo'),
    ('bi', 'bis', None, 'Bislama'),
    (None, 'bla', None, 'Siksika'),
    (None, 'bnt', None, 'Bantu (Other)'),
    ('bo', 'bod', 'tib', 'Tibetan'),
    ('bs', 'bos', None, 'Bosnian'),
    (None, 'bra', None, 'Braj'),
    ('br', 'bre', None, 'Breton'),
    (None, 'btk', None, 'Batak languages'),
    (None, 'bua', None, 'Buriat'),
    (None, 'bug', None, 'Buginese'),
    ('bg', 'bul', None, 'Bulgarian'),
    (None, 'byn', None, 'Blin; Bilin'),
    (None, 'cad', None, 'Caddo'),
    (None, 'cai', None, 'Central American Indian languages'),
    (None, 'car', None, 'Galibi Carib'),
    ('ca', 'cat', None, 'Catalan; Valencian'),
    (None, 'cau', None, 'Caucasian languages'),
    (None, 'ceb', None, 'Cebuano'),
    (None, 'cel', None, 'Celtic languages'),
    ('cs', 'ces', 'cze', 'Czech'),
    ('ch', 'cha', None, 'Chamorro'),
    (None, 'chb', None, 'Chibcha'),
    ('ce', 'che', None, 'Chechen'),
    (None, 'chg', None, 'Chagatai'),
    (None, 'chk', None, 'Chuukese'),
    (None, 'chm', None, 'Mari'),
    (None, 'chn', None, 'Chinook jargon'),
    (None, 'cho', None, 'Choctaw'),
    (None, 'chp', None, 'Chipewyan; Dene Suline'),
    (None, 'chr', None, 'Cherokee'),
    ('cu', 'chu', None, 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'),
    ('cv', 'chv', None, 'Chuvash'),
    (None, 'chy', None, 'Cheyenne'),
    (None, 'cmc', None, 'Chamic languages'),
    (None, 'cnr', None, 'Montenegrin'),
    (None, 'cop', None, 'Coptic'),
    ('kw', 'cor', None, 'Cornish'),
    ('co', 'cos', None, 'Corsican'),
    (None, 'cpe', None, 'Creoles and pidgins, English based'),
    (None, 'cpf', None, 'Creoles and pidgins, French-based'),
    (None, 'cpp', None, 'Creoles and pidgins, Portuguese-based'),
    ('cr', 'cre', None, 'Cree'),
    (None, 'crh', None, 'Crimean Tatar; Crimean Turkish'),
    (None, 'crp', None, 'Creoles and pidgins'),
    (None, 'csb', None, 'Kashubian'),
    (None, 'cus', None, 'Cushitic languages'),
    ('cy', 'cym', 'wel', 'Welsh'),
    (None, 'dak', None, 'Dakota'),
    ('da', 'dan', None, 'Danish'),
    (None, 'dar', None, 'Dargwa'),
    (None, 'day', None, 'Land Dayak languages'),
    (None, 'del', None, 'Delaware'),
    (None, 'den', None, 'Slave (Athapascan)'),
    ('de', 'deu', 'ger', 'German'),
    (None, 'dgr', None, 'Dogrib'),
    (None, 'din', None, 'Dinka'),
    ('dv', 'div', None, 'Divehi; Dhivehi; Maldivian'),
    (None, 'doi', None, 'Dogri'),
    (None, 'dra', None, 'Dravidian languages'),
    (None, 'dsb', None, 'Lower Sorbian'),
    (None, 'dua', None, 'Duala'),
    (None, 'dum', None, 'Dutch, Middle (ca. 1050-1350)'),
    (None, 'dyu', None, 'Dyula'),
    ('dz', 'dzo', None, 'Dzongkha'),
    (None, 'efi', None, 'Efik'),
    (None, 'egy', None, 'Egyptian (Ancient)'),
    (None, 'eka', None, 'Ekajuk'),
    ('el', 'ell', 'gre', 'Greek, Modern (1453-)'),
    (None, 'elx', None, 'Elamite'),
    ('en', 'eng', None, 'English'),
    (None, 'enm', None, 'English, Middle (1100-1500)'),
    ('eo', 'epo', None, 'Esperanto'),
    ('et', 'est', None, 'Estonian'),
    ('eu', 'eus', 'baq', 'Basque'),
    ('ee', 'ewe', None, 'Ewe'),
    (None, 'ewo', None, 'Ewondo'),
    (None, 'fan', None, 'Fang'),
    ('fo', 'fao', None, 'Faroese'),
    ('fa', 'fas', 'per', 'Persian'),
    (None, 'fat', None, 'Fanti'),
    ('fj', 'fij', None, 'Fijian'),
    (None, 'fil', None, 'Filipino; Pilipino'),
    ('fi', 'fin', None, 'Finnish'),
    (None, 'fiu', None, 'Finno-Ugrian languages'),
    (None, 'fon', None, 'Fon'),
    ('fr', 'fra', 'fre', 'French'),
    (None, 'frm', None, 'French, Middle (ca. 1400-1600)'),
    (None, 'fro', None, 'French, Old (842-ca. 1400)'),
    (None, 'frr', None, 'Northern Frisian'),
    (None, 'frs', None, 'Eastern Frisian'),
    ('fy', 'fry', None, 'Western Frisian'),
    ('ff', 'ful', None, 'Fulah'),
    (None, 'fur', None, 'Friulian'),
    (None, 'gaa', None, 'Ga'),
    (None, 'gay', None, 'Gayo'),
    (None, 'gba', None, 'Gbaya'),
    (None, 'gem', None, 'Germanic languages'),
    (None, 'gez', None, 'Geez'),
    (None, 'gil', None, 'Gilbertese'),
    ('gd', 'gla', None, 'Gaelic; Scottish Gaelic'),
    ('ga', 'gle', None, 'Irish'),
    ('gl', 'glg', None, 'Galician'),
    ('gv', 'glv', None, 'Manx'),
    (None, 'gmh', None, 'German, Middle High (ca. 1050-1500)'),
    (None, 'goh', None, 'German, Old High (ca. 750-1050)'),
    (None, 'gon', None, 'Gondi'),
    (None, 'gor', None, 'Gorontalo'),
    (None, 'got', None, 'Gothic'),
    (None, 'grb', None, 'Grebo'),
    (None, 'grc', None, 'Greek, Ancient (to 1453)'),
    ('gn', 'grn', None, 'Guarani'),
    (None, 'gsw', None, 'Swiss German; Alemannic; Alsatian'),
    ('gu', 'guj', None, 'Gujarati'),
    (None, 'gwi', None, "Gwich'in"),
    (None, 'hai', None, 'Haida'),
    ('ht', 'hat', None, 'Haitian; Haitian Creole'),
    ('ha', 'hau', None, 'Hausa'),
    (None, 'haw', None, 'Hawaiian'),
    ('he', 'heb', None, 'Hebrew'),
    ('hz', 'her', None, 'Herero'),
    (None, 'hil', None, 'Hiligaynon'),
    (None, 'him', None, 'Himachali languages; Western Pahari languages'),
    ('hi', 'hin', None, 'Hindi'),
    (None, 'hit', None, 'Hittite'),
    (None, 'hmn', None, 'Hmong; Mong'),
    ('ho', 'hmo', None, 'Hiri Motu'),
    ('hr', 'hrv', None, 'Croatian'),
    (None, 'hsb', None, 'Upper Sorbian'),
    ('hu', 'hun', None, 'Hungarian'),
    (None, 'hup', None, 'Hupa'),
    ('hy', 'hye', 'arm', 'Armenian'),
    (None, 'iba', None, 'Iban'),
    ('ig', 'ibo', None, 'Igbo'),
    ('io', 'ido', None, 'Ido'),
    ('ii', 'iii', None, 'Sichuan Yi; Nuosu'),
    (None, 'ijo', None, 'Ijo languages'),
    ('iu', 'iku', None, 'Inuktitut'),
    ('ie', 'ile', None, 'Interlingue; Occidental'),
    (None, 'ilo', None, 'Iloko'),
    ('ia', 'ina', None, 'Interlingua (International Auxiliary Language Association)'),
    (None, 'inc', None, 'Indic languages'),
    ('id', 'ind', None, 'Indonesian'),
    (None, 'ine', None, 'Indo-European languages'),
    (None, 'inh', None, 'Ingush'),
    ('ik', 'ipk', None, 'Inupiaq'),
    (None, 'ira', None, 'Iranian languages'),
    (None, 'iro', None, 'Iroquoian languages'),
    ('is', 'isl', 'ice', 'Icelandic'),
    ('it', 'ita', None, 'Italian'),
    ('jv', 'jav', None, 'Javanese'),
    (None, 'jbo', None, 'Lojban'),
    ('ja', 'jpn', None, 'Japanese'),
    (None, 'jpr', None, 'Judeo-Persian'),
    (None, 'jrb', None, 'Judeo-Arabic'),
    (None, 'kaa', None, 'Kara-Kalpak'),
    (None, 'kab', None, 'Kabyle'),
    (None, 'kac', None, 'Kachin; Jingpho'),
    ('kl', 'kal', None, 'Kalaallisut; Greenlandic'),
    (None, 'kam', None, 'Kamba'),
    ('kn', 'kan', None, 'Kannada'),
    (None, 'kar', None, 'Karen languages'),
    ('ks', 'kas', None, 'Kashmiri'),
    ('ka', 'kat', 'geo', 'Georgian'),
    ('kr', 'kau', None, 'Kanuri'),
    (None, 'kaw', None, 'Kawi'),
    ('kk', 'kaz', None, 'Kazakh'),
    (None, 'kbd', None, 'Kabardian'),
    (None, 'kha', None, 'Khasi'),
    (None, 'khi', None, 'Khoisan languages'),
    ('km', 'khm', None, 'Central Khmer'),
    (None, 'kho', None, 'Khotanese; Sakan'),
    ('ki', 'kik', None, 'Kikuyu; Gikuyu'),
    ('rw', 'kin', None, 'Kinyarwanda'),
    ('ky', 'kir', None, 'Kirghiz; Kyrgyz'),
    (None, 'kmb', None, 'Kimbundu'),
    (None, 'kok', None, 'Konkani'),
    ('kv', 'kom', None, 'Komi'),
    ('kg', 'kon', None, 'Kongo'),
    ('ko', 'kor', None, 'Korean'),
    (None, 'kos', None, 'Kosraean'),
    (None, 'kpe', None, 'Kpelle'),
    (None, 'krc', None, 'Karachay-Balkar'),
    (None, 'krl', None, 'Karelian'),
    (None, 'kro', None, 'Kru languages'),
    (None, 'kru', None, 'Kurukh'),
    ('kj', 'kua', None, 'Kuanyama; Kwanyama'),
    (None, 'kum', None, 'Kumyk'),
    ('ku', 'kur', None, 'Kurdish'),
    (None, 'kut', None, 'Kutenai'),
    (None, 'lad', None, 'Ladino'),
    (None, 'lah', None, 'Lahnda'),
    (None, 'lam', None, 'Lamba'),
    ('lo', 'lao', None, 'Lao'),
    ('la', 'lat', None, 'Latin'),
    ('lv', 'lav', None, 'Latvian'),
    (None, 'lez', None, 'Lezghian'),
    ('li', 'lim', None, 'Limburgan; Limburger; Limburgish'),
    ('ln', 'lin', None, 'Lingala'),
    ('lt', 'lit', None, 'Lithuanian'),
    (None, 'lol', None, 'Mongo'),
    (None, 'loz', None, 'Lozi'),
    ('lb', 'ltz', None, 'Luxembourgish; Letzeburgesch'),
    (None, 'lua', None, 'Luba-Lulua'),
    ('lu', 'lub', None, 'Luba-Katanga'),
    ('lg', 'lug', None, 'Ganda'),
    (None, 'lui', None, 'Luiseno'),
    (None, 'lun', None, 'Lunda'),
    (None, 'luo', None, 'Luo (Kenya and Tanzania)'),
    (None, 'lus', None, 'Lushai'),
    (None, 'mad', None, 'Madurese'),
    (None, 'mag', None, 'Magahi'),
    ('mh', 'mah', None, 'Marshallese'),
    (None, 'mai', None, 'Maithili'),
    (None, 'mak', None, 'Makasar'),
    ('ml', 'mal', None, 'Malayalam'),
    (None, 'man', None, 'Mandingo'),
    (None, 'map', None, 'Austronesian languages'),
    ('mr', 'mar', None, 'Marathi'),
    (None, 'mas', None, 'Masai'),
    (None, 'mdf', None, 'Moksha'),
    (None, 'mdr', None, 'Mandar'),
    (None, 'men', None, 'Mende'),
    (None, 'mga', None, 'Irish, Middle (900-1200)'),
    (None, 'mic', None, "Mi'kmaq; Micmac"),
    (None, 'min', None, 'Minangkabau'),
    (None, 'mis', None, 'Uncoded languages'),
    ('mk', 'mkd', 'mac', 'Macedonian'),
    (None, 'mkh', None, 'Mon-Khmer languages'),
    ('mg', 'mlg', None, 'Malagasy'),
    ('mt', 'mlt', None, 'Maltese'),
    (None, 'mnc', None, 'Manchu'),
    (None, 'mni', None, 'Manipuri'),
    (None, 'mno', None, 'Manobo languages'),
    (None, 'moh', None, 'Mohawk'),
    ('mn', 'mon', None, 'Mongolian'),
    (None, 'mos', None, 'Mossi'),
    ('mi', 'mri', 'mao', 'Maori'),
    ('ms', 'msa', 'may', 'Malay'),
    (None, 'mul', None, 'Multiple languages'),
    (None, 'mun', None, 'Munda languages'),
    (None, 'mus', None, 'Creek'),
    (None, 'mwl', None, 'Mirandese'),
    (None, 'mwr', None, 'Marwari'),
    ('my', 'mya', 'bur', 'Burmese'),
    (None, 'myn', None, 'Mayan languages'),
    (None, 'myv', None, 'Erzya'),
    (None, 'nah', None, 'Nahuatl languages'),
    (None, 'nai', None, 'North American Indian languages'),
    (None, 'nap', None, 'Neapolitan'),
    ('na', 'nau', None, 'Nauru'),
    ('nv', 'nav', None, 'Navajo; Navaho'),
    ('nr', 'nbl', None, 'Ndebele, South; South Ndebele'),
    ('nd', 'nde', None, 'Ndebele, North; North Ndebele'),
    ('ng', 'ndo', None, 'Ndonga'),
    (None, 'nds', None, 'Low German; Low Saxon; German, Low; Saxon, Low'),
    ('ne', 'nep', None, 'Nepali'),
    (None, 'new', None, 'Nepal Bhasa; Newari'),
    (None, 'nia', None, 'Nias'),
    (None, 'nic', None, 'Niger-Kordofanian languages'),
    (None, 'niu', None, 'Niuean'),
    ('nl', 'nld', 'dut', 'Dutch; Flemish'),
    ('nn', 'nno', None, 'Norwegian Nynorsk; Nynorsk, Norwegian'),
    ('nb', 'nob', None, 'Bokmål, Norwegian; Norwegian Bokmål'),
    (None, 'nog', None, 'Nogai'),
    (None, 'non', None, 'Norse, Old'),
    ('no', 'nor', None, 'Norwegian'),
    (None, 'nqo', None, "N'Ko"),
    (None, 'nso', None, 'Pedi; Sepedi; Northern Sotho'),
    (None, 'nub', None, 'Nubian languages'),
    (None, 'nwc', None, 'Classical Newari; Old Newari; Classical Nepal Bhasa'),
    ('ny', 'nya', None, 'Chichewa; Chewa; Nyanja'),
    (None, 'nym', None, 'Nyamwezi'),
    (None, 'nyn', None, 'Nyankole'),
    (None, 'nyo', None, 'Nyoro'),
    (None, 'nzi', None, 'Nzima'),
    ('oc', 'oci', None, 'Occitan (post 1500); Provençal'),
    ('oj', 'oji', None, 'Ojibwa'),
    ('or', 'ori', None, 'Oriya'),
    ('om', 'orm', None, 'Oromo'),
    (None, 'osa', None, 'Osage'),
    ('os', 'oss', None, 'Ossetian; Ossetic'),
    (None, 'ota', None, 'Turkish, Ottoman (1500-1928)'),
    (None, 'oto', None, 'Otomian languages'),
    (None, 'paa', None, 'Papuan languages'),
    (None, 'pag', None, 'Pangasinan'),
    (None, 'pal', None, 'Pahlavi'),
    (None, 'pam', None, 'Pampanga; Kapampangan'),
    ('pa', 'pan', None, 'Panjabi; Punjabi'),
    (None, 'pap', None, 'Papiamento'),
    (None, 'pau', None, 'Palauan'),
    (None, 'peo', None, 'Persian, Old (ca. 600-400 B.C.)'),
    (None, 'phi', None, 'Philippine languages'),
    (None, 'phn', None, 'Phoenician'),
    ('pi', 'pli', None, 'Pali'),
    ('pl', 'pol', None, 'Polish'),
    (None, 'pon', None, 'Pohnpeian'),
    ('pt', 'por', None, 'Portuguese'),
    (None, 'pra', None, 'Prakrit languages'),
    (None, 'pro', None, 'Provençal, Old (to 1500)'),
    ('ps', 'pus', None, 'Pushto; Pashto'),
    (None, 'qaa-qtz', None, 'Reserved for local use'),
    ('qu', 'que', None, 'Quechua'),
    (None, 'raj', None, 'Rajasthani'),
    (None, 'rap', None, 'Rapanui'),
    (None, 'rar', None, 'Rarotongan; Cook Islands Maori'),
    (None, 'roa', None, 'Romance languages'),
    ('rm', 'roh', None, 'Romansh'),
    (None, 'rom', None, 'Romany'),
    ('ro', 'ron', 'rum', 'Romanian; Moldavian; Moldovan'),
    ('rn', 'run', None, 'Rundi'),
    (None, 'rup', None, 'Aromanian; Arumanian; Macedo-Romanian'),
    ('ru', 'rus', None, 'Russian'),
    (None, 'sad', None, 'Sandawe'),
    ('sg', 'sag', None, 'Sango'),
    (None, 'sah', None, 'Yakut'),
    (None, 'sai', None, 'South American Indian (Other)'),
    (None, 'sal', None, 'Salishan languages'),
    (None, 'sam', None, 'Samaritan Aramaic'),
    ('sa', 'san', None, 'Sanskrit'),
    (None, 'sas', None, 'Sasak'),
    (None, 'sat', None, 'Santali'),
    (None, 'scn', None, 'Sicilian'),
    (None, 'sco', None, 'Scots'),
    (None, 'sel', None, 'Selkup'),
    (None, 'sem', None, 'Semitic languages'),
    (None, 'sga', None, 'Irish, Old (to 900)'),
    (None, 'sgn', None, 'Sign Languages'),
    (None, 'shn', None, 'Shan'),
    (None, 'sid', None, 'Sidamo'),
    ('si', 'sin', None, 'Sinhala; Sinhalese'),
    (None, 'sio', None, 'Siouan languages'),
    (None, 'sit', None, 'Sino-Tibetan languages'),
    (None, 'sla', None, 'Slavic languages'),
    ('sk', 'slk', 'slo', 'Slovak'),
    ('sl', 'slv', None, 'Slovenian'),
    (None, 'sma', None, 'Southern Sami'),
    ('se', 'sme', None, 'Northern Sami'),
    (None, 'smi', None, 'Sami languages'),
    (None, 'smj', None, 'Lule Sami'),
    (None, 'smn', None, 'Inari Sami'),
    ('sm', 'smo', None, 'Samoan'),
    (None, 'sms', None, 'Skolt Sami'),
    ('sn', 'sna', None, 'Shona'),
    ('sd', 'snd', None, 'Sindhi'),
    (None, 'snk', None, 'Soninke'),
    (None, 'sog', None, 'Sogdian'),
    ('so', 'som', None, 'Somali'),
    (None, 'son', None, 'Songhai languages'),
    ('st', 'sot', None, 'Sotho, Southern'),
    ('es', 'spa', None, 'Spanish; Castilian'),
    ('sq', 'sqi', 'alb', 'Albanian'),
    ('sc', 'srd', None, 'Sardinian'),
    (None, 'srn', None, 'Sranan Tongo'),
    ('sr', 'srp', None, 'Serbian'),
    (None, 'srr', None, 'Serer'),
    (None, 'ssa', None, 'Nilo-Saharan languages'),
    ('ss', 'ssw', None, 'Swati'),
    (None, 'suk', None, 'Sukuma'),
    ('su', 'sun', None, 'Sundanese'),
    (None, 'sus', None, 'Susu'),
    (None, 'sux', None, 'Sumerian'),
    ('sw', 'swa', None, 'Swahili'),
    ('sv', 'swe', None, 'Swedish'),
    (None, 'syc', None, 'Classical Syriac'),
    (None, 'syr', None, 'Syriac'),
    ('ty', 'tah', None, 'Tahitian'),
    (None, 'tai', None, 'Tai languages'),
    ('ta', 'tam', None, 'Tamil'),
    ('tt', 'tat', None, 'Tatar'),
    ('te', 'tel', None, 'Telugu'),
    (None, 'tem', None, 'Timne'),
    (None, 'ter', None, 'Tereno'),
    (None, 'tet', None, 'Tetum'),
    ('tg', 'tgk', None, 'Tajik'),
    ('tl', 'tgl', None, 'Tagalog'),
    ('th', 'tha', None, 'Thai'),
    (None, 'tig', None, 'Tigre'),
    ('ti', 'tir', None, 'Tigrinya'),
    (None, 'tiv', None, 'Tiv'),
    (None, 'tkl', None, 'Tokelau'),
    (None, 'tlh', None, 'Klingon; tlhIngan-Hol'),
    (None, 'tli', None, 'Tlingit'),
    (None, 'tmh', None, 'Tamashek'),
    (None, 'tog', None, 'Tonga (Nyasa)'),
    ('to', 'ton', None, 'Tonga (Tonga Islands)'),
    (None, 'tpi', None, 'Tok Pisin'),
    (None, 'tsi', None, 'Tsimshian'),
    ('tn', 'tsn', None, 'Tswana'),
    ('ts', 'tso', None, 'Tsonga'),
    ('tk', 'tuk', None, 'Turkmen'),
    (None, 'tum', None, 'Tumbuka'),
    (None, 'tup', None, 'Tupi languages'),
    ('tr', 'tur', None, 'Turkish'),
    (None, 'tut', None, 'Altaic languages'),
    (None, 'tvl', None, 'Tuvalu'),
    ('tw', 'twi', None, 'Twi'),
    (None, 'tyv', None, 'Tuvinian'),
    (None, 'udm', None, 'Udmurt'),
    (None, 'uga', None, 'Ugaritic'),
    ('ug', 'uig', None, 'Uighur; Uyghur'),
    ('uk', 'ukr', None, 'Ukrainian'),
    (None, 'umb', None, 'Umbundu'),
    (None, 'und', None, 'Undetermined'),
    ('ur', 'urd', None, 'Urdu'),
    ('uz', 'uzb', None, 'Uzbek'),
    (None, 'vai', None, 'Vai'),
    ('ve', 'ven', None, 'Venda'),
    ('vi', 'vie', None, 'Vietnamese'),
    ('vo', 'vol', None, 'Volapük'),
    (None, 'vot', None, 'Votic'),
    (None, 'wak', None, 'Wakashan languages'),
    (None, 'wal', None, 'Walamo'),
    (None, 'war', None, 'Waray'),
    (None, 'was', None, 'Washo'),
    (None, 'wen', None, 'Sorbian languages'),
    ('wa', 'wln', None, 'Walloon'),
    ('wo', 'wol', None, 'Wolof'),
    (None, 'xal', None, 'Kalmyk; Oirat'),
    ('xh', 'xho', None, 'Xhosa'),
    (None, 'yao', None, 'Yao'),
    (None, 'yap', None, 'Yapese'),
    ('yi', 'yid', None, 'Yiddish'),
    ('yo', 'yor', None, 'Yoruba'),
    (None, 'ypk', None, 'Yupik languages'),
    (None, 'zap', None, 'Zapotec'),
    (None, 'zbl', None, 'Blissymbols; Blissymbolics; Bliss'),
    (None, 'zen', None, 'Zenaga'),
    (None, 'zgh', None, 'Standard Moroccan Tamazight'),
    ('za', 'zha', None, 'Zhuang; Chuang'),
    ('zh', 'zho', 'chi', 'Chinese'),
    (None, 'znd', None, 'Zande languages'),
    ('zu', 'zul', None, 'Zulu'),
    (None, 'zun', None, 'Zuni'),
    (None, 'zxx', None, 'No linguistic content; Not applicable'),
    (None, 'zza', None, 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki'),
)
